
#Screen Config
[screen]
	#Blur GUI background when opening a gui screen, this is incompatible with OptiFine's FXAA shader or some mods.
	blurGuiBackground = true
	#Keep game running no matter what screen is open. Modern UI's GUIs will never pause game.
	keepGameRunning = true
	#A list of gui screen superclasses that won't activate blur effect when opened.
	blurGuiExclusions = []

#Fonts Config
[fonts]
	#Allow font renderer to draw text with shadow, set to false if you can't read the font clearly.
	allowFontShadow = true
	#The name of font to use with highest priority. The default font that included in Modern UI is always the alternative one to use.
	preferredFontName = ""
	#Replace vanilla's font renderer to Modern UI's. This won't affect the font renderer which is used in Modern UI's GUIs.
	enableGlobalRenderer = true

